spring:
  profiles: produce
  datasource:
      url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
      username: sa
      password: 
      initialize: false

logging:
  level: warn
  config: config/logback-spring.xml
